# Generated by Django 3.0.6 on 2020-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0002_remove_employee_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
