# Generated by Django 3.0.6 on 2020-05-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0002_auto_20200517_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='address_number',
            field=models.IntegerField(),
        ),
    ]
