# Generated by Django 3.0.6 on 2020-05-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0003_auto_20200517_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostumerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('costumer', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='trabalho3.Costumer')),
                ('product', models.ManyToManyField(default='null', to='trabalho3.Product')),
            ],
            options={
                'db_table': 'costumer_bill',
            },
        ),
        migrations.CreateModel(
            name='ProviderBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
                ('product', models.ManyToManyField(default='null', to='trabalho3.Product')),
                ('provider', models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='trabalho3.Provider')),
            ],
            options={
                'db_table': 'provider_bill',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
