# Generated by Django 3.0.6 on 2020-05-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('enumber', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'costumer',
            },
        ),
    ]
