# Generated by Django 3.0.6 on 2020-05-17 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0004_auto_20200517_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderBillProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalho3.ProviderBill')),
                ('provider_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalho3.Product')),
            ],
        ),
        migrations.CreateModel(
            name='CostumerBillProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costumer_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalho3.CostumerBill')),
                ('costumer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trabalho3.Product')),
            ],
        ),
    ]
