# Generated by Django 3.0.6 on 2020-05-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0004_costumer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eprice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'bill',
            },
        ),
    ]
