# Generated by Django 3.0.6 on 2020-05-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0005_bill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='eprice',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='costumer',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='costumer',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='costumer',
            old_name='enumber',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='enumber',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ename',
            new_name='name',
        ),
    ]
