# Generated by Django 3.0.6 on 2020-05-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0005_costumerbillproduct_providerbillproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerbillproduct',
            name='provider_bill',
        ),
        migrations.RemoveField(
            model_name='providerbillproduct',
            name='provider_product',
        ),
        migrations.DeleteModel(
            name='CostumerBillProduct',
        ),
        migrations.DeleteModel(
            name='ProviderBillProduct',
        ),
    ]
