# Generated by Django 3.0.6 on 2020-05-16 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0006_auto_20200514_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='costumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trabalho3.Costumer'),
            preserve_default=False,
        ),
    ]
