# Generated by Django 3.0.6 on 2020-05-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabalho3', '0007_auto_20200517_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providerbill',
            name='provider',
        ),
    ]
